/* =============================================================
   config.js — LOCAL DEVELOPMENT ONLY
   ⚠️  This file is git-ignored. NEVER commit it to GitHub.
   ⚠️  In production this file is generated by GitHub Actions
       using the MY_GITHUB_TOKEN secret — see .github/workflows/deploy.yml

   HOW TO USE LOCALLY:
   1. Copy this file (it already exists if you're reading it)
   2. Fill in your real token and repo below
   3. Open index.html in your browser — push/pull will work
   ============================================================= */

window.__TRIBUTE_CONFIG__ = {
  token:  'YOUR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',   // paste your GitHub PAT here (local only)
  repo:   'kevinkutoyi/teresinaaloomulaa',   // e.g. 'kevinkutoyi/teresinaaloomulaa'
  branch: 'main',
  path:   'data.json'
};
